### ISSUE TITLE
Непрерывная интеграция через ShareLatex

### ISSUE THREAD

**Issue by ulysses4ever** [siamezzze/bachelor_presentation#1]
Может, сделаете? Пример виден в [ридми этого репа](https://github.com/MMCS-SFEDU/mmcs_sfedu_thesis): там шильдик PDF build зелёненький с ссылкой на ШареЛатех, этот сайт моментально цепляется к аккаунту на ГХ.

**Comment by siamezzze** [comment]
Вроде как-то сделала, хоть и не так красиво получилось.

**Comment by ulysses4ever** [comment]
О, здорово, это даже лучше, чем я умею. Только у вас две ссылки на один и тот же PDF с текстом, а хотелось бы и презентацию!

**Comment by siamezzze** [comment]
Уфф, да, это что-то я сама в своих репозиториях запуталась. Вроде исправила, спасибо!
