### ISSUE TITLE
Много списков

### ISSUE THREAD

**Issue by ulysses4ever** [siamezzze/bachelor_presentation#3]
Маша! Я бы советовал вам разбавить текст какими-то визуальными элементами (картинками, таблицами и т.п.). Тем более, у вас распознавание образов.

**Comment by siamezzze** [comment]
Угу, есть такое. То, что тут сейчас, ближе к плану презентации. 
Раздумываю, на самом деле, сейчас над иллюстрациями. Кроме, очевидно, самих эллипсов, хочется вставить графиков с временем работы - вот как раз сейчас читаю, с помощью чего бы их сделать.
Спасибо.

**Comment by siamezzze** [comment]
Подозреваю, иллюстрации из используемых статей нельзя даже с указанием источников?

**Comment by ulysses4ever** [comment]
Иллюстрации можно любые. Указание источников опционально. Это же не текст
диплома, это просто техническое средство донесения идей до публики. Грубо
говоря, вы могли бы на защите открыть чужую статью и что-то
продемонстировать, но это долго, потому применяют презентации.

**Comment by siamezzze** [comment]
Сейчас должно быть лучше, добавила изображений и формул. Подумаю, что ещё сделать.
